# Functions in Tensorflow

In [2]:
import tensorflow as tf

In [3]:
t= tf.constant([[1,2,3], [4,5,6]])
tf.is_tensor(t)

True

In [4]:
a= [1,2,3]
tf.is_tensor(a)

False

In [5]:
def my_func(arg):
    arg = tf.convert_to_tensor(arg, dtype=tf.float32)
    return arg

In [6]:
my_func(a)

<tf.Tensor: shape=(3,), dtype=float32, numpy=array([1., 2., 3.], dtype=float32)>

In [7]:
x= tf.constant([1.8, 2.2], dtype=tf.float32)
print(x)

tf.Tensor([1.8 2.2], shape=(2,), dtype=float32)


In [8]:
tf.dtypes.cast(x, tf.int32)

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([1, 2])>

In [9]:
t1= [[1,2,3], [4,5,6]]
t2 = [[7,8,9], [10,11,12]]
tf.concat([t1,t2], 0)

<tf.Tensor: shape=(4, 3), dtype=int32, numpy=
array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])>

In [10]:
t1= [[1,2,3], [4,5,6]]
t2 = [[7,8,9], [10,11,12]]
tf.concat([t1,t2], 1)

<tf.Tensor: shape=(2, 6), dtype=int32, numpy=
array([[ 1,  2,  3,  7,  8,  9],
       [ 4,  5,  6, 10, 11, 12]])>

In [11]:
tf.fill([2,3], 0)

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[0, 0, 0],
       [0, 0, 0]])>

In [12]:
tf.eye(2)

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[1., 0.],
       [0., 1.]], dtype=float32)>

In [13]:
tf.linspace(10.0, 12.0, 3, name = "linspace")

<tf.Tensor: shape=(3,), dtype=float32, numpy=array([10., 11., 12.], dtype=float32)>

In [14]:
indices = [0,1,2]
depth = 3
tf.one_hot(indices, depth)

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]], dtype=float32)>

In [15]:
tf.ones([3,4], tf.int32)

<tf.Tensor: shape=(3, 4), dtype=int32, numpy=
array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])>

In [16]:
tensor = tf.constant([[1,2,3], [4,5,6]])
tf.ones_like(tensor)

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[1, 1, 1],
       [1, 1, 1]])>

In [17]:
start = 3
limit = 18
delta = 3
tf.range(start, limit, delta)

<tf.Tensor: shape=(5,), dtype=int32, numpy=array([ 3,  6,  9, 12, 15])>

In [18]:
t = tf.constant([1,2,3,4,5])
tf.size(t)

<tf.Tensor: shape=(), dtype=int32, numpy=5>