# Neural Network Model for Beginners

1- Build a neural network that classify images

2- Train this neural network

3- And, finally, evaluate the accuracy of the model.

In [1]:
import tensorflow as tf

In [2]:
mnist = tf.keras.datasets.mnist

In [3]:
# Split the data set
(X_train, y_train), (X_test, y_test)= mnist.load_data()

In [4]:
print(X_train)

[[[0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  ...
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]]

 [[0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  ...
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]]

 [[0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  ...
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]]

 ...

 [[0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  ...
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]]

 [[0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  ...
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]]

 [[0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  ...
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]]]


In [5]:
type(X_train)

numpy.ndarray

In [10]:
model = tf.keras.models.Sequential([
    tf.keras.layers.Flatten(input_shape = (28,28)),
    tf.keras.layers.Dense(128, activation = "relu"),
    tf.keras.layers.Dropout(0.2),
    tf.keras.layers.Dense(10)
])

In [13]:
predictions = model(X_train[:1]).numpy()
print(predictions)

[[ -83.506775   60.437943   -8.68405   145.96738    36.27892    59.251484
  -154.698     -71.9418    -91.48236    18.77829 ]]


In [15]:
tf.nn.softmax(predictions).numpy()

<tf.Tensor: shape=(1, 10), dtype=float32, numpy=
array([[0.0000000e+00, 7.1620723e-38, 0.0000000e+00, 1.0000000e+00,
        0.0000000e+00, 2.1865762e-38, 0.0000000e+00, 0.0000000e+00,
        0.0000000e+00, 0.0000000e+00]], dtype=float32)>

In [16]:
loss_fn = tf.keras.losses.SparseCategoricalCrossentropy(from_logits= True)

In [17]:
loss_fn(y_train[:1], predictions).numpy()

86.7159

In [18]:
# Compile model
model.compile(optimizer= "adam",
             loss = loss_fn,
             metrics = ["accuracy"])

In [21]:
model.fit(X_train, y_train, epochs = 20)

Epoch 1/20
1875/1875 [==============================] - 3s 2ms/step - loss: 0.3299 - accuracy: 0.9189
Epoch 2/20
1875/1875 [==============================] - 3s 2ms/step - loss: 0.3179 - accuracy: 0.9215
Epoch 3/20
1875/1875 [==============================] - 3s 2ms/step - loss: 0.3219 - accuracy: 0.9214
Epoch 4/20
1875/1875 [==============================] - 3s 2ms/step - loss: 0.3035 - accuracy: 0.9253
Epoch 5/20
1875/1875 [==============================] - 3s 2ms/step - loss: 0.3052 - accuracy: 0.9238
Epoch 6/20
1875/1875 [==============================] - 3s 2ms/step - loss: 0.3040 - accuracy: 0.9257
Epoch 7/20
1875/1875 [==============================] - 3s 2ms/step - loss: 0.3061 - accuracy: 0.9250
Epoch 8/20
1875/1875 [==============================] - 3s 2ms/step - loss: 0.2945 - accuracy: 0.9265
Epoch 9/20
1875/1875 [==============================] - 3s 2ms/step - loss: 0.2866 - accuracy: 0.9287
Epoch 10/20
1875/1875 [==============================] - 3s 2ms/step - loss: 0.297

In [22]:
# Model evaluation
model.evaluate(X_test, y_test, verbose=2)

313/313 - 0s - loss: 0.4359 - accuracy: 0.9425


[0.4358767569065094, 0.9424999952316284]