# Random Number Generator

In [2]:
import tensorflow as tf

In [3]:
g = tf.random.Generator.from_seed(1234)
g.normal(shape=(2,3))

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[ 0.9356609 ,  1.0854305 , -0.93788373],
       [-0.5061547 ,  1.3169702 ,  0.7137579 ]], dtype=float32)>

In [13]:
samples = tf.random.categorical(tf.math.log([[0.5, 0.5]]),5)
print(samples)

tf.Tensor([[0 1 1 0 0]], shape=(1, 5), dtype=int64)


In [15]:
samples = tf.random.gamma([10], [0.5, 1.5])
print(samples)

tf.Tensor(
[[0.6886381  2.287305  ]
 [0.01430319 0.9921987 ]
 [0.6153091  1.8891839 ]
 [0.00468624 1.4972364 ]
 [0.25813714 0.5936209 ]
 [0.24143161 1.9633505 ]
 [0.59806484 1.4848603 ]
 [1.2489866  2.529931  ]
 [0.58829814 1.009141  ]
 [0.06021811 0.8564499 ]], shape=(10, 2), dtype=float32)


In [16]:
samples = tf.random.poisson([10], [0.5, 1.5])
print(samples)

tf.Tensor(
[[0. 1.]
 [0. 0.]
 [2. 0.]
 [0. 2.]
 [0. 1.]
 [0. 3.]
 [0. 3.]
 [0. 1.]
 [0. 4.]
 [0. 1.]], shape=(10, 2), dtype=float32)


In [17]:
tf.random.uniform(shape=[2])

<tf.Tensor: shape=(2,), dtype=float32, numpy=array([0.22751772, 0.5011414 ], dtype=float32)>