In [1]:
import tensorflow as tf

In [2]:
strng = tf.constant("DeepLearning")

In [3]:
print(strng)

tf.Tensor(b'DeepLearning', shape=(), dtype=string)


In [4]:
tf.strings.length(strng)

<tf.Tensor: shape=(), dtype=int32, numpy=12>

In [5]:
tf.strings.lower(strng)

<tf.Tensor: shape=(), dtype=string, numpy=b'deeplearning'>

In [6]:
tf.strings.upper(strng)

<tf.Tensor: shape=(), dtype=string, numpy=b'DEEPLEARNING'>

In [7]:
tf.strings.split("hello world")

<tf.Tensor: shape=(2,), dtype=string, numpy=array([b'hello', b'world'], dtype=object)>

In [8]:
tf.strings.unicode_decode(strng, "UTF8")

<tf.Tensor: shape=(12,), dtype=int32, numpy=array([ 68, 101, 101, 112,  76, 101,  97, 114, 110, 105, 110, 103])>

In [9]:
list_array= tf.constant(["tensorflow", "keras", "pytorch"])
for i in list_array:
    print(i)

tf.Tensor(b'tensorflow', shape=(), dtype=string)
tf.Tensor(b'keras', shape=(), dtype=string)
tf.Tensor(b'pytorch', shape=(), dtype=string)


In [10]:
tf.strings.to_number("10.5")

<tf.Tensor: shape=(), dtype=float32, numpy=10.5>