### What is Tensorflow?

Tensorflow is an open source deep learning library developed by google

It is known as tensorflow because it takes multi dimensional array as an input 

### What are Tensors?

Tensors are multi dimensional array

A vector is a one dimensional tensor

A matrix is a two dimensional tensor

In [1]:
import tensorflow as tf

In [2]:
x= tf.constant(5)

In [3]:
print(x)

tf.Tensor(5, shape=(), dtype=int32)


In [4]:
x= tf.constant(5.0)

In [5]:
print(x)

tf.Tensor(5.0, shape=(), dtype=float32)


In [6]:
x = tf.constant(5, shape= (1,1))
print(x)

tf.Tensor([[5]], shape=(1, 1), dtype=int32)


In [7]:
x= tf.constant(5, shape=(1,1), dtype= tf.float32)
print(x)

tf.Tensor([[5.]], shape=(1, 1), dtype=float32)


In [10]:
x= tf.constant([[1,2,3], [4,5,6]])
print(x)

tf.Tensor(
[[1 2 3]
 [4 5 6]], shape=(2, 3), dtype=int32)


In [11]:
x= tf.zeros((2,2))
print(x)

tf.Tensor(
[[0. 0.]
 [0. 0.]], shape=(2, 2), dtype=float32)


In [12]:
x= tf.ones((2,2))
print(x)

tf.Tensor(
[[1. 1.]
 [1. 1.]], shape=(2, 2), dtype=float32)


In [13]:
x= tf.eye(3)
print(x)

tf.Tensor(
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]], shape=(3, 3), dtype=float32)


In [16]:
x= tf.random.normal((2,2), mean=0, stddev=1)
print(x)

tf.Tensor(
[[-0.5279222  -0.84975725]
 [-1.6658082  -1.5413982 ]], shape=(2, 2), dtype=float32)


In [17]:
x= tf.range(10)
print(x)

tf.Tensor([0 1 2 3 4 5 6 7 8 9], shape=(10,), dtype=int32)


In [18]:
x= tf.range(start=1, limit=20, delta=3)
print(x)

tf.Tensor([ 1  4  7 10 13 16 19], shape=(7,), dtype=int32)


In [19]:
y = tf.cast(x, dtype= tf.float64)
print(y)

tf.Tensor([ 1.  4.  7. 10. 13. 16. 19.], shape=(7,), dtype=float64)
