In [2]:
import tensorflow as tf

In [3]:
tf_variable = tf.Variable([[1,2,3], [4,5,6]])
print(tf_variable)

<tf.Variable 'Variable:0' shape=(2, 3) dtype=int32, numpy=
array([[1, 2, 3],
       [4, 5, 6]])>


In [4]:
bool_variable = tf.Variable([True, False, True, False])
print(bool_variable)

<tf.Variable 'Variable:0' shape=(4,) dtype=bool, numpy=array([ True, False,  True, False])>


In [5]:
complex_variable = tf.Variable([5+4j, 6+1j])
print(complex_variable)

<tf.Variable 'Variable:0' shape=(2,) dtype=complex128, numpy=array([5.+4.j, 6.+1.j])>


In [6]:
print(tf_variable.shape)

(2, 3)


In [7]:
print(tf_variable.dtype)

<dtype: 'int32'>


In [8]:
print(tf_variable.numpy)

<bound method BaseResourceVariable.numpy of <tf.Variable 'Variable:0' shape=(2, 3) dtype=int32, numpy=
array([[1, 2, 3],
       [4, 5, 6]])>>


In [11]:
tf_variable = tf.Variable([[1,2,3], [4,5,6]])
print(tf_variable)

<tf.Variable 'Variable:0' shape=(2, 3) dtype=int32, numpy=
array([[1, 2, 3],
       [4, 5, 6]])>


In [12]:
print(tf.reshape(tf_variable, ([3,2])))

tf.Tensor(
[[1 2]
 [3 4]
 [5 6]], shape=(3, 2), dtype=int32)


In [13]:
a= tf.Variable([2,20,30,3,6])
print(a)

<tf.Variable 'Variable:0' shape=(5,) dtype=int32, numpy=array([ 2, 20, 30,  3,  6])>


In [15]:
print(tf.argmax(a))

tf.Tensor(2, shape=(), dtype=int64)


In [16]:
print(tf.argmin(a))

tf.Tensor(0, shape=(), dtype=int64)


In [17]:
a = tf.Variable([2.0, 3.0])
print(a)

<tf.Variable 'Variable:0' shape=(2,) dtype=float32, numpy=array([2., 3.], dtype=float32)>


In [18]:
b = tf.Variable(a)
print(b)

<tf.Variable 'Variable:0' shape=(2,) dtype=float32, numpy=array([2., 3.], dtype=float32)>


In [19]:
a.assign([5,6])
print(a)

<tf.Variable 'Variable:0' shape=(2,) dtype=float32, numpy=array([5., 6.], dtype=float32)>


In [20]:
print(b)

<tf.Variable 'Variable:0' shape=(2,) dtype=float32, numpy=array([2., 3.], dtype=float32)>


In [21]:
print(a.numpy())

[5. 6.]


In [23]:
print(b.numpy())

[2. 3.]


In [24]:
a_gradient = tf.Variable(1, trainable = False)

In [25]:
with tf.device("CPU:0"):
    a = tf.Variable([[1.0, 2.0, 3.0], [4.0, 5.0,6.0]])
    b = tf.Variable([[1.0,2.0], [3.0,4.0], [5.0, 6.0]])
    c = tf.matmul(a,b)
print(c)

tf.Tensor(
[[22. 28.]
 [49. 64.]], shape=(2, 2), dtype=float32)
